name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "Raspberry Pi 32-bit"
          id: "32bit"  
        - name: "Raspberry Pi 64-bit"
          id: "64bit" 

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from file
        id: get_version
        run: |
          VERSION=$(cut -d "'" -f2 < pwnagotchi/_version.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install qemu dependencies
        run: sudo apt update && sudo apt install qemu-user-static qemu-utils xz-utils -y

      - name: Build ${{ matrix.name }} img file
        run: ls -la .; pwd; make packer; make ${{ matrix.id }}

      - name: Transfer ${{ matrix.name }} .img to docker and give permissions
        run: sudo chown runner:docker "pwnagotchi-${{ matrix.id }}.img"

      - name: PiShrink
        run: |
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
          chmod +x pishrink.sh
          sudo mv pishrink.sh /usr/local/bin
          find /home/runner/work/ -type f -name "pwnagotchi-${{ matrix.id }}.img" -exec sudo pishrink.sh -aZ {} \;

      - name: Change name of .img.xz to add version
        run: mv "pwnagotchi-${{ matrix.id }}.img.xz" "pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}.img.xz"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          make_latest: true
          tag_name: v${{ env.VERSION }}
          name: Pwnagotchi v${{ env.VERSION }}
          files: pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}.img.xz
          generate_release_notes: true
